POS_UNIVERSAL_GOOGLE = ['ADJ',
                        'ADP',
                        'ADV',
                        'AUX',
                        # 'CCONJ',
                        'CONJ',
                        'DET',
                        'INTJ',
                        'NOUN',
                        'NUM',
                        'PART',
                        'PRON',
                        'PROPN',
                        'PUNCT',
                        'SCONJ',
                        'SYM',
                        'VERB',
                        'X',
                        'SPACE']
