UTS_TAGSET = ['ADJ',
              'ADP',
              'ADV',
              'CONJ',
              'DET',
              'NOUN',
              'NUM',
              'PRON',
              'PRT',
              'VERB',
              'X',
              'DOT']

STTS_UTS_Mapping = {'Interpunction_Comma': 'DOT',
                    'Interpunction_SentenceEnd': 'DOT',
                    'Interpunction_SentenceIntern': 'DOT',
                    'ADJA': 'ADJ',
                    'ADJD': 'ADJ',
                    'ADV': 'ADV',
                    'APPO': 'ADP',
                    'APPR': 'ADP',
                    'APPRART': 'ADP',
                    'APZR': 'ADP',
                    'ART': 'DET',
                    'CARD': 'NUM',
                    'FM': 'X',
                    'ITJ': 'X',
                    'KOKOM': 'CONJ',
                    'KON': 'CONJ',
                    'KOUI': 'CONJ',
                    'KOUS': 'CONJ',
                    'NE': 'NOUN',
                    'NN': 'NOUN',
                    'PDAT': 'PRON',
                    'PDS': 'PRON',
                    'PIAT': 'PRON',
                    'PIS': 'PRON',
                    'PPER': 'PRON',
                    'PPOSAT': 'PRON',
                    'PPOSS': 'PRON',
                    'PRELAT': 'PRON',
                    'PRELS': 'PRON',
                    'PRF': 'PRON',
                    'PROAV': 'PRON',
                    'PTKA': 'PRT',
                    'PTKANT': 'PRT',
                    'PTKNEG': 'PRT',
                    'PTKVZ': 'PRT',
                    'PTKZU': 'PRT',
                    'PWAT': 'PRON',
                    'PWAV': 'PRON',
                    'PWS': 'PRON',
                    'TRUNC': 'X',
                    'VAFIN': 'VERB',
                    'VAIMP': 'VERB',
                    'VAINF': 'VERB',
                    'VAPP': 'VERB',
                    'VMFIN': 'VERB',
                    'VMINF': 'VERB',
                    'VMPP': 'VERB',
                    'VVFIN': 'VERB',
                    'VVIMP': 'VERB',
                    'VVINF': 'VERB',
                    'VVIZU': 'VERB',
                    'VVPP': 'VERB',
                    'XY': 'X'}


def get_UTS_tag(STTS_tag):
    return STTS_UTS_Mapping[STTS_tag]
